### PR TITLE
Refactoring and improvements

### PR DESCRIPTION
**Pull request by foxweb**
1. `.gitignore` added.
2. BASIC sources renamed to `*.bas` with lowercase.
3. Small styling and formatting sources according NASA C Style Guide.
4. Pause function added to game of Snake.
5. `charset.bas` added.

### CODE REVIEW

**Comment by fbergama** [comment]
Hi foxweb, thank you for the pr. It looks good at a first sight. I'll merge it as soon as I check that everything is ok :+1:

**Comment by foxweb** [comment]
I think about splitting `BASIC-Programs` from this repo and move it into `RC2014-BASIC-Programs` repo or remove the latter and develop `BASIC-Programs` in this repo. Or include it as submodule.

**Comment by fbergama** [comment]
The `RC2014-BASIC-Programs` repo is still there for compatibility reasons. We decided to put all the RC2014 stuff (basic programs/c software etc) in this repo. So feel free to develop all your basic programs here in `BASIC-Program` subdir

**Comment by fbergama** [comment]
I've seen that your changes to the snake game goes beyond simple code style refactoring. Have you tested it on a real RC2014?
I'd rather perform two separate merges. One for code style refactoring and one for the snake, so I have time to test it separately

**Comment by foxweb** [comment]
> Have you tested it on a real RC2014?

Yes, I have one RC2014 from Spencer recently :)

img_3651

img_3649

> I'd rather perform two separate merges. One for code style refactoring and one for the snake, so I have time to test it separately

Ok, how to I do it better? I can recover `snake.c` from you `master` for this pr and create new pr with updated `snake.c` only.

**Comment by fbergama** [comment]
It's ok, I just wanted to be sure to commit something that is working properly  :) 
Looks like everything is fine, I proceed with the merge.

**Pull request merged**
